import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
<<<<<<< HEAD
=======
import Navbar from "./components/Navbar";
>>>>>>> 084e6d06905fe6f5e3e046070e70a91b479d3bdf

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
=======
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar/>
>>>>>>> 084e6d06905fe6f5e3e046070e70a91b479d3bdf
        {children}
      </body>
    </html>
  );
<<<<<<< HEAD
}
=======
}
>>>>>>> 084e6d06905fe6f5e3e046070e70a91b479d3bdf
